### ISSUE TITLE
What is the license of this lib?

### ISSUE THREAD

**Issue by lisael** [JelleZijlstra/ast_decompiler#13]
Without a license, we can use it only in toy projects, it's a shame, because I think it's a much needed library. Thank you!

**Comment by JelleZijlstra** [comment]
Looks like I put it under Apache 2.0 (https://github.com/JelleZijlstra/ast_decompiler/blob/master/setup.py#L19). I guess we should also have a LICENSE file though.

**Comment by lisael** [comment]
Ha sorry, I didn't even peak into the setup.py file or the pypi page. Bad habits from github usage I guess. Thank you!
