### ISSUE TITLE
Support python3.9

### ISSUE THREAD

**Issue by lisael** [JelleZijlstra/ast_decompiler#14]
I'd need python 3.9 support. I'd like to contribute, ~~but #13 must be sorted out before I start investing time on this.~~

EDIT: #13 is sloved to me

**Comment by JelleZijlstra** [comment]
Go ahead, thanks for working on this! Let me know if you need help with anything.

**Comment by JelleZijlstra** [comment]
And I'll be happy to cut a release after 3.9 support is in a good place.

**Comment by lisael** [comment]
At the moment tests fail on extended slices. This led me to this python issue: https://bugs.python.org/issue39520

That's how I learnt about https://docs.python.org/3/library/ast.html#ast.unparse which is quite a big deal for `ast_decompiler` ;)

**Comment by JelleZijlstra** [comment]
Oh right, good point! `ast_decompiler` does have a few more options than `ast.unparse`, so it may still be useful independently.

**Comment by JelleZijlstra** [comment]
With #28 Python 3.9 syntax is fully supported.
